# SPDX-FileCopyrightText: 2025 Matthew Mark Ibbetson
# SPDX-FileContributor: Matthew Mark Ibbetson
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "litr"
SPDX-PackageSupplier = "Matthew Mark Ibbetson <mmibbetson@gmail.com>"

[[annotations]]
path = ".gitattributes"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Matthew Mark Ibbetson"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "docs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Matthew Mark Ibbetson"
SPDX-License-Identifier = "GPL-3.0-or-later"
